---
- name: Inspect interfaces
  ansible.builtin.import_tasks: interfaces.yml

- name: Inspect bridges
  ansible.builtin.import_tasks: bridges.yml

- name: Validate network configuration
  ansible.builtin.import_tasks: validate.yml
  when: network_validate_lan

- name: Configure LAN
  ansible.builtin.import_tasks: lan.yml
  when: network_manage_lan

- name: Configure IoT Network
  ansible.builtin.import_tasks: iot.yml
  when: network_manage_iot
