---
- name: Configure IoT firewall
  ansible.builtin.import_tasks: iot.yml
  when: firewall_manage_iot

- name: Configure IoT forwarding
  ansible.builtin.import_tasks: iot-forwarding.yml
  when: firewall_manage_iot

- name: Configure IoT services
  ansible.builtin.import_tasks: iot-services.yml
  when: firewall_manage_iot

- name: Configure MQTT firewall access
  ansible.builtin.import_tasks: mqtt.yml
  when: firewall_manage_mqtt

- name: Remove legacy MQTT firewall access
  ansible.builtin.import_tasks: mqtt-remove.yml
  when: not firewall_manage_mqtt

- name: Configure MQTT TLS firewall access
  ansible.builtin.import_tasks: mqtt_tls.yml
  when: firewall_manage_mqtt_tls
