---
system_manage_hostname: true
system_hostname: flint2

system_manage_timezone: true
system_zonename: Europe/Berlin
system_timezone: CET-1CEST,M3.5.0.M10.5.0/3

dropbear_manage_password_auth: true
dropbear_password_auth: "0"

dropbear_manage_root_password_auth: true
dropbear_root_password_auth: "0"

dropbear_manage_root_login: true
dropbear_root_login: "1"

packages_install:
  - nano

network_validate_lan: true
network_expected_lan_ip: 192.168.8.1
network_expected_lan_proto: static

network_manage_lan: true
network_lan_proto: static
network_lan_ipaddr: 192.168.8.1

network_manage_iot: true
network_iot_disabled: "0"
network_iot_ipaddr: 192.168.10.1
network_iot_netmask: 255.255.255.0
