---
name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  permissions:
    contents: read

  jobs:
    validate:
      name: Validate Anisble
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v7

        - name: Build Ansible container
          run: docker build -t flint2-ansible .

        - name: Check check-router playbook syntax
          run: | 
            docker run --rm \
              --entrypoint ansible-playbook \
              -v "${{ github.workspace }}:/ansible" \
              flint2-ansible \
              -i inventory/hosts.ini \
              playbooks/check-router.yml \
              --syntax-check
